### PR TITLE
Add a horror tale when dead code is not removed

### PR DESCRIPTION
**Pull request by elhoyos**
In the context of dead code, feature toggles could hide old code that if active could carry on significant damage.

Here's a reference to an U.S. Securities and Exchange Commission act where they order the cease and desist to a company that lost more than 400 million in trading transactions due to a repurposed "flag".

I believe this fits here, rather than in OEP-17, because this OEP-21 is somehow a detailed expansion of the "Removal" section in OEP-17 and most importantly, this OEP-21 includes a broader solution to mitigate the risk. The horror tale may also apply to configurations options and not necessarily toggles.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @elhoyos! I've created [OSPR-4077](https://openedx.atlassian.net/browse/OSPR-4077) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@elhoyos Thank you for your proposal. I will queue this for our review.

**Comment by elhoyos** [comment]
@natabene, just did so. Please let me know if it works.

**Comment by natabene** [comment]
@elhoyos Great, thank you! It may take them several days to process, and once we are all set, we will you know here and via email.

**Comment by natabene** [comment]
@elhoyos Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Comment by natabene** [comment]
@elhoyos I am queueing your PR for our review, please stay tuned.

**Comment by natabene** [comment]
@ormsbee @dianakhuang Is this something either of you could review?

**Comment by nasthagiri** [comment]
@elhoyos Thanks for updating the OEP and good luck with your thesis on toggles!

**Comment by edx-webhook** [comment]
@elhoyos 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/open-edx-proposals&entry.867055334=https://github.com/edx/open-edx-proposals/pull/132&entry.1484655318=https://github.com/elhoyos&entry.752974735=2020-02-04+03:00&entry.1917517419=2020-02-05+22:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
