### PR TITLE
Add a Change History section to OEP-1

### PR DESCRIPTION
**Pull request by cpennington**
@nedbat, @efagin: Review?

### CODE REVIEW

**Comment by efagin** [comment]
👍 as a follow up item, we should consider opening PRs against all outstanding OEPs, after this merges, that adds a change history section to each of them.

**Comment by nedbat** [comment]
:+1:

**Comment by cpennington** [comment]
@efagin: I think I'll actually just add a section to each of them as part of this PR. No need for the extra step.

**Comment by efagin** [comment]
@cpennington that's fine with me, I was just noting that you didn't _need_ to do all of that yourself! But if you want to, be my guest - it's appreciated. :)

**Comment by jzoldak** [comment]
👍

**Pull request merged**
