### PR TITLE
Improve guidance on when to start an OEP

### PR DESCRIPTION
**Pull request by shaunagm**
I've separated out the steps for brainstorming an OEP & getting feedback from the actual process of submission.  The main reason for this PR is that I'd like clearer guidance as to what kind of suggestions make for good OEPs.  I've added a section for examples but cannot populate it myself, as I do not know what makes for a good or bad OEPs.

### CODE REVIEW

**Comment by efagin** [comment]
@cpennington as the original OEP-1 author, would you mind working with @shaunagm to resolve this PR that updates OEP-1? If not, please just let me know and I'll find somebody else.

**Comment by cpennington** [comment]
@efagin: Well, I failed to get this done before @shaunagm left, but I'll try and work up some examples.

**Comment by efagin** [comment]
@cpennington bump

**Comment by efagin** [comment]
I'm going to close this PR due to lack of activity. The changes are minimal and we should consider revisiting this if we experience commons barriers to entry on OEPs.

**Pull request closed without merging**
