### PR TITLE
OEP-0026: Real-time Events (Caliper)

### PR DESCRIPTION
**Pull request by danialmalik**
Adding Open edX Proposal OEP-26 for Real-time Events, primarily for Adaptive Learning capabilities.

### Motivation
Caliper Analytics enables institutions to collect learning data from digital resources to better understand and visualize learning activity and product usage data, and present this information to students, instructors, and advisors in meaningful ways to help them improve the learning experience.
This PR adds the Caliper specifications as it hadn't already been along with xAPI (#73).

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @danialmalik! I've created [OSPR-4579](https://openedx.atlassian.net/browse/OSPR-4579) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@danialmalik Thank you for your contribution. @nasthagiri @marcotuts How would you like to proceed with this?

**Comment by nasthagiri** [comment]
@natabene Please assign the review of this to me. I plan to do so this week. Thanks!

**Comment by nasthagiri** [comment]
@brianhw As arbiter of OEP-26, do you have any other requests on this PR before we merge?

**Comment by danialmalik** [comment]
@nasthagiri I've updated the PR and have added my self as one of the contributors in the PR.

**Comment by edx-webhook** [comment]
@danialmalik 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/open-edx-proposals&entry.867055334=https://github.com/edx/open-edx-proposals/pull/152&entry.1484655318=https://github.com/danialmalik&entry.752974735=2020-05-22+15:43&entry.1917517419=2020-06-04+19:13&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
